apiVersion: v1
kind: Service
metadata:
  name: my-sample-app-service
  labels:
    app: my-sample-app
spec:
  selector:
    app: my-sample-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
