apiVersion: apps/v1
kind: Deployment
metadata:
  name: helios
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helios
  template:
    metadata:
      labels:
        app: helios
    spec:
      containers:
      - name: app
        image: docker.io/hophuochoan/helios:main@sha256:1dfd93879f3eab13471004d2f5e38bc7ae1c471408db5704b55fee32d2cf7932
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helios
  namespace: default
spec:
  selector:
    app: helios
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
