apiVersion: apps/v1
kind: Deployment
metadata:
  name: helios
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helios
  template:
    metadata:
      labels:
        app: helios
    spec:
      containers:
      - name: app
        image: docker.io/hophuochoan/helios:15419f60b0384cdc51bdd56fdf31c1475b289bfb@sha256:fff09382c3162e9ffe71e6ae3fc5fe7eb76dde50ace69afc0001bdabbad6fa4a
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helios
  namespace: default
spec:
  selector:
    app: helios
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
