apiVersion: apps/v1
kind: Deployment
metadata:
  name: helios
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helios
  template:
    metadata:
      labels:
        app: helios
    spec:
      containers:
      - name: app
        image: docker.io/hophuochoan/helios:7ca03c77c39e5162342a9c109c71360bb3c000a6@sha256:1de16d1f6c58fd009de2c9de30eafafd74c1aa41d92275bc90953d49bdb6a9c6
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helios
  namespace: default
spec:
  selector:
    app: helios
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
