apiVersion: apps/v1
kind: Deployment
metadata:
  name: helios
spec:
  replicas: 5
  selector:
    matchLabels:
      app: helios
  template:
    metadata:
      labels:
        app: helios
    spec:
      containers:
        - name: app
          image: docker.io/hophuochoan/helios:main@sha256:29fbfbb4229d501f1cd631e4640033e49545a45d58900ebc6bac475a03f876ac
          ports:
            - containerPort: 1000
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '500m'
---
apiVersion: v1
kind: Service
metadata:
  name: helios
spec:
  selector:
    app: helios
  ports:
    - port: 80
      targetPort: 1000
