apiVersion: apps/v1
kind: Deployment
metadata:
  name: helios
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helios
  template:
    metadata:
      labels:
        app: helios
    spec:
      containers:
        - name: app
          image: docker.io/hophuochoan/helios:main@sha256:217647d387db4e6d5bee9801e56f32ec1648928b7645f5db2186daa0d82e47c9
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '500m'
---
apiVersion: v1
kind: Service
metadata:
  name: helios
spec:
  selector:
    app: helios
  ports:
    - port: 80
      targetPort: 8080
